"""College Fest domain baseline task dependencies."""
from typing import List
from app.domains.types import DependencyDefinition, DependencyType

COLLEGE_FEST_DEPENDENCIES: List[DependencyDefinition] = [
    DependencyDefinition(
        predecessor_key="college_fest.venue_prep",
        successor_key="college_fest.stage_setup",
        dependency_type=DependencyType.FINISH_TO_START,
        lag_minutes=0,
    ),
    DependencyDefinition(
        predecessor_key="college_fest.venue_prep",
        successor_key="college_fest.power_setup",
        dependency_type=DependencyType.FINISH_TO_START,
        lag_minutes=0,
    ),
    DependencyDefinition(
        predecessor_key="college_fest.venue_prep",
        successor_key="college_fest.security_prep",
        dependency_type=DependencyType.FINISH_TO_START,
        lag_minutes=30,
    ),
    DependencyDefinition(
        predecessor_key="college_fest.venue_prep",
        successor_key="college_fest.registration_setup",
        dependency_type=DependencyType.FINISH_TO_START,
        lag_minutes=30,
    ),
    DependencyDefinition(
        predecessor_key="college_fest.venue_prep",
        successor_key="college_fest.catering_setup",
        dependency_type=DependencyType.FINISH_TO_START,
        lag_minutes=30,
    ),
    DependencyDefinition(
        predecessor_key="college_fest.stage_setup",
        successor_key="college_fest.equipment_setup",
        dependency_type=DependencyType.FINISH_TO_START,
        lag_minutes=0,
    ),
    DependencyDefinition(
        predecessor_key="college_fest.power_setup",
        successor_key="college_fest.equipment_setup",
        dependency_type=DependencyType.FINISH_TO_START,
        lag_minutes=0,
    ),
    DependencyDefinition(
        predecessor_key="college_fest.equipment_setup",
        successor_key="college_fest.sound_setup",
        dependency_type=DependencyType.FINISH_TO_START,
        lag_minutes=0,
    ),
    DependencyDefinition(
        predecessor_key="college_fest.equipment_setup",
        successor_key="college_fest.lighting_setup",
        dependency_type=DependencyType.FINISH_TO_START,
        lag_minutes=0,
    ),
    DependencyDefinition(
        predecessor_key="college_fest.sound_setup",
        successor_key="college_fest.technical_checks",
        dependency_type=DependencyType.FINISH_TO_START,
        lag_minutes=0,
    ),
    DependencyDefinition(
        predecessor_key="college_fest.lighting_setup",
        successor_key="college_fest.technical_checks",
        dependency_type=DependencyType.FINISH_TO_START,
        lag_minutes=0,
    ),
    DependencyDefinition(
        predecessor_key="college_fest.technical_checks",
        successor_key="college_fest.final_readiness",
        dependency_type=DependencyType.FINISH_TO_START,
        lag_minutes=0,
    ),
    DependencyDefinition(
        predecessor_key="college_fest.security_prep",
        successor_key="college_fest.final_readiness",
        dependency_type=DependencyType.FINISH_TO_START,
        lag_minutes=0,
    ),
    DependencyDefinition(
        predecessor_key="college_fest.registration_setup",
        successor_key="college_fest.final_readiness",
        dependency_type=DependencyType.FINISH_TO_START,
        lag_minutes=0,
    ),
    DependencyDefinition(
        predecessor_key="college_fest.catering_setup",
        successor_key="college_fest.final_readiness",
        dependency_type=DependencyType.FINISH_TO_START,
        lag_minutes=0,
    ),
]
