"""College Fest domain baseline operational tasks."""
from typing import List
from app.domains.types import TaskDefinition
from app.models.enums import TaskPriority

COLLEGE_FEST_TASKS: List[TaskDefinition] = [
    TaskDefinition(
        key="college_fest.venue_prep",
        name="Ground Clearance & Venue Preparation",
        description="Clear festival zone, verify emergency exits, deploy trash bins and portaloos",
        priority=TaskPriority.CRITICAL,
        phase="SETUP",
        required_provider_category="venue",
        is_critical=True,
        estimated_duration_minutes=120,
    ),
    TaskDefinition(
        key="college_fest.power_setup",
        name="High-Voltage Power Distribution",
        description="Position diesel generators, earth electrical grounding, run 3-phase power distribution",
        priority=TaskPriority.CRITICAL,
        phase="SETUP",
        required_provider_category="power",
        is_critical=True,
        estimated_duration_minutes=120,
    ),
    TaskDefinition(
        key="college_fest.stage_setup",
        name="Main Stage & Roof Canopy Construction",
        description="Assemble heavy steel stage framing, level platform deck, and erect roof truss structure",
        priority=TaskPriority.CRITICAL,
        phase="SETUP",
        required_provider_category="stage",
        is_critical=True,
        estimated_duration_minutes=240,
    ),
    TaskDefinition(
        key="college_fest.equipment_setup",
        name="Truss Rigging & Equipment Mounting",
        description="Mount motorized chain hoists, elevate truss grids, secure safety cables and ground drops",
        priority=TaskPriority.HIGH,
        phase="SETUP",
        required_provider_category="equipment",
        is_critical=True,
        estimated_duration_minutes=90,
    ),
    TaskDefinition(
        key="college_fest.sound_setup",
        name="Concert Sound Reinforcement Rigging",
        description="Fly line-array speaker hangs, place front-fill subs, set stage monitors and snake cables",
        priority=TaskPriority.CRITICAL,
        phase="SETUP",
        required_provider_category="sound",
        is_critical=True,
        estimated_duration_minutes=120,
    ),
    TaskDefinition(
        key="college_fest.lighting_setup",
        name="Stage Lighting & Effects Setup",
        description="Rig profile and wash moving heads, patch DMX universe, test blinders and haze machines",
        priority=TaskPriority.HIGH,
        phase="SETUP",
        required_provider_category="lighting",
        is_critical=False,
        estimated_duration_minutes=90,
    ),
    TaskDefinition(
        key="college_fest.security_prep",
        name="Barricade Installation & Security Briefing",
        description="Install heavy pit barricades, set perimeter fences, brief bouncers and medical teams",
        priority=TaskPriority.CRITICAL,
        phase="SETUP",
        required_provider_category="security",
        is_critical=True,
        estimated_duration_minutes=60,
    ),
    TaskDefinition(
        key="college_fest.registration_setup",
        name="Gate Entry & Ticket Verification Setup",
        description="Set up entry canopies, barcode scanners, wristband tables, and queue stanchions",
        priority=TaskPriority.HIGH,
        phase="SETUP",
        required_provider_category="logistics",
        is_critical=False,
        estimated_duration_minutes=60,
    ),
    TaskDefinition(
        key="college_fest.technical_checks",
        name="Integrated Acoustic & Lighting Checks",
        description="Perform full-volume frequency sweeps, wireless mic RF scans, and light cue playback",
        priority=TaskPriority.HIGH,
        phase="SETUP",
        required_provider_category="sound",
        is_critical=True,
        estimated_duration_minutes=60,
    ),
    TaskDefinition(
        key="college_fest.catering_setup",
        name="Food Stalls & Hydration Zone Setup",
        description="Inspect vendor hygiene, verify food court power supply, stock free drinking water stations",
        priority=TaskPriority.MEDIUM,
        phase="SETUP",
        required_provider_category="catering",
        is_critical=False,
        estimated_duration_minutes=60,
    ),
    TaskDefinition(
        key="college_fest.final_readiness",
        name="Festival Operations Readiness Verification",
        description="Final multi-agency safety walkthrough and formal sign-off before gates open",
        priority=TaskPriority.CRITICAL,
        phase="SETUP",
        required_provider_category="venue",
        is_critical=True,
        estimated_duration_minutes=30,
    ),
]
