"""Wedding domain baseline operational tasks."""
from typing import List
from app.domains.types import TaskDefinition, ObjectivePriority

WEDDING_TASKS: List[TaskDefinition] = [
    TaskDefinition(
        key="wedding.venue_prep",
        name="Venue Preparation and Access",
        description="Unlock venue, inspect clean condition, verify HVAC and restrooms",
        priority=ObjectivePriority.CRITICAL,
        phase="SETUP",
        required_provider_category="VENUE",
        is_critical=True,
        estimated_duration_minutes=90,
    ),
    TaskDefinition(
        key="wedding.power_setup",
        name="Power Infrastructure Setup",
        description="Connect generators, route heavy cables, and test electrical capacity",
        priority=ObjectivePriority.CRITICAL,
        phase="SETUP",
        required_provider_category="AV_LIGHTING",
        is_critical=True,
        estimated_duration_minutes=60,
    ),
    TaskDefinition(
        key="wedding.decor_setup",
        name="Decoration & Floral Setup",
        description="Erect mandap/arch, place centerpieces, floral arches, and drape backdrops",
        priority=ObjectivePriority.HIGH,
        phase="SETUP",
        required_provider_category="DECOR",
        is_critical=False,
        estimated_duration_minutes=180,
    ),
    TaskDefinition(
        key="wedding.seating_setup",
        name="Guest Seating & Dining Layout Setup",
        description="Position tables, arrange banquet chairs, align place cards",
        priority=ObjectivePriority.HIGH,
        phase="SETUP",
        required_provider_category="LOGISTICS",
        is_critical=False,
        estimated_duration_minutes=90,
    ),
    TaskDefinition(
        key="wedding.catering_setup",
        name="Catering & Bar Station Setup",
        description="Prepare warming stations, set cutlery, chill beverages, and stock service bar",
        priority=ObjectivePriority.HIGH,
        phase="SETUP",
        required_provider_category="CATERING",
        is_critical=True,
        estimated_duration_minutes=120,
    ),
    TaskDefinition(
        key="wedding.sound_music_setup",
        name="Audio & Sound System Setup",
        description="Install PA speakers, configure wireless mics, and set DJ/band station",
        priority=ObjectivePriority.HIGH,
        phase="SETUP",
        required_provider_category="ENTERTAINMENT",
        is_critical=False,
        estimated_duration_minutes=75,
    ),
    TaskDefinition(
        key="wedding.sound_check",
        name="Acoustic and Sound Check",
        description="Test officiant microphones, background music volume, and feedback elimination",
        priority=ObjectivePriority.MEDIUM,
        phase="SETUP",
        required_provider_category="ENTERTAINMENT",
        is_critical=False,
        estimated_duration_minutes=30,
    ),
    TaskDefinition(
        key="wedding.photo_video_setup",
        name="Photography & Lighting Calibration",
        description="Set photography fill lights, scout ceremony angles, and calibrate cameras",
        priority=ObjectivePriority.MEDIUM,
        phase="SETUP",
        required_provider_category="PHOTOGRAPHY",
        is_critical=False,
        estimated_duration_minutes=45,
    ),
    TaskDefinition(
        key="wedding.ceremony_prep",
        name="Ceremony Ritual Preparation",
        description="Prepare ceremonial items, sacred fire/altar, ring cushions, and aisle runner",
        priority=ObjectivePriority.CRITICAL,
        phase="SETUP",
        required_provider_category="DECOR",
        is_critical=True,
        estimated_duration_minutes=60,
    ),
    TaskDefinition(
        key="wedding.guest_area_prep",
        name="Guest Welcome & Reception Area Setup",
        description="Set registration/guestbook table, welcome signs, and champagne station",
        priority=ObjectivePriority.MEDIUM,
        phase="SETUP",
        required_provider_category="LOGISTICS",
        is_critical=False,
        estimated_duration_minutes=45,
    ),
    TaskDefinition(
        key="wedding.readiness_check",
        name="Final Wedding Readiness Verification",
        description="Comprehensive operational walkthrough with couple/planner before guest arrival",
        priority=ObjectivePriority.CRITICAL,
        phase="SETUP",
        required_provider_category="VENUE",
        is_critical=True,
        estimated_duration_minutes=30,
    ),
]
