"""Conference domain baseline task dependencies."""
from typing import List
from app.domains.types import DependencyDefinition, DependencyType

CONFERENCE_DEPENDENCIES: List[DependencyDefinition] = [
    DependencyDefinition(
        predecessor_key="conference.venue_setup",
        successor_key="conference.seating_setup",
        dependency_type=DependencyType.FINISH_TO_START,
        lag_minutes=0,
    ),
    DependencyDefinition(
        predecessor_key="conference.venue_setup",
        successor_key="conference.stage_setup",
        dependency_type=DependencyType.FINISH_TO_START,
        lag_minutes=0,
    ),
    DependencyDefinition(
        predecessor_key="conference.venue_setup",
        successor_key="conference.power_setup",
        dependency_type=DependencyType.FINISH_TO_START,
        lag_minutes=0,
    ),
    DependencyDefinition(
        predecessor_key="conference.venue_setup",
        successor_key="conference.registration_setup",
        dependency_type=DependencyType.FINISH_TO_START,
        lag_minutes=15,
    ),
    DependencyDefinition(
        predecessor_key="conference.venue_setup",
        successor_key="conference.catering_setup",
        dependency_type=DependencyType.FINISH_TO_START,
        lag_minutes=30,
    ),
    DependencyDefinition(
        predecessor_key="conference.power_setup",
        successor_key="conference.av_setup",
        dependency_type=DependencyType.FINISH_TO_START,
        lag_minutes=0,
    ),
    DependencyDefinition(
        predecessor_key="conference.power_setup",
        successor_key="conference.connectivity_check",
        dependency_type=DependencyType.FINISH_TO_START,
        lag_minutes=0,
    ),
    DependencyDefinition(
        predecessor_key="conference.stage_setup",
        successor_key="conference.display_setup",
        dependency_type=DependencyType.FINISH_TO_START,
        lag_minutes=0,
    ),
    DependencyDefinition(
        predecessor_key="conference.av_setup",
        successor_key="conference.mic_setup",
        dependency_type=DependencyType.FINISH_TO_START,
        lag_minutes=0,
    ),
    DependencyDefinition(
        predecessor_key="conference.av_setup",
        successor_key="conference.display_setup",
        dependency_type=DependencyType.FINISH_TO_START,
        lag_minutes=0,
    ),
    DependencyDefinition(
        predecessor_key="conference.mic_setup",
        successor_key="conference.final_tech_check",
        dependency_type=DependencyType.FINISH_TO_START,
        lag_minutes=0,
    ),
    DependencyDefinition(
        predecessor_key="conference.display_setup",
        successor_key="conference.final_tech_check",
        dependency_type=DependencyType.FINISH_TO_START,
        lag_minutes=0,
    ),
    DependencyDefinition(
        predecessor_key="conference.connectivity_check",
        successor_key="conference.final_tech_check",
        dependency_type=DependencyType.FINISH_TO_START,
        lag_minutes=0,
    ),
    DependencyDefinition(
        predecessor_key="conference.seating_setup",
        successor_key="conference.readiness_verification",
        dependency_type=DependencyType.FINISH_TO_START,
        lag_minutes=0,
    ),
    DependencyDefinition(
        predecessor_key="conference.registration_setup",
        successor_key="conference.readiness_verification",
        dependency_type=DependencyType.FINISH_TO_START,
        lag_minutes=0,
    ),
    DependencyDefinition(
        predecessor_key="conference.catering_setup",
        successor_key="conference.readiness_verification",
        dependency_type=DependencyType.FINISH_TO_START,
        lag_minutes=0,
    ),
    DependencyDefinition(
        predecessor_key="conference.final_tech_check",
        successor_key="conference.readiness_verification",
        dependency_type=DependencyType.FINISH_TO_START,
        lag_minutes=0,
    ),
]
