"""Conference domain baseline operational tasks."""
from typing import List
from app.domains.types import TaskDefinition, ObjectivePriority

CONFERENCE_TASKS: List[TaskDefinition] = [
    TaskDefinition(
        key="conference.venue_setup",
        name="Venue Access & Main Hall Handover",
        description="Receive convention hall keys, inspect breakout room locks, test climate control",
        priority=ObjectivePriority.CRITICAL,
        phase="SETUP",
        required_provider_category="VENUE",
        is_critical=True,
        estimated_duration_minutes=90,
    ),
    TaskDefinition(
        key="conference.power_setup",
        name="AV Power Distribution & Stage Drops",
        description="Run isolated clean power feeds to audio racks, video switchers, and keynote lectern",
        priority=ObjectivePriority.CRITICAL,
        phase="SETUP",
        required_provider_category="POWER",
        is_critical=True,
        estimated_duration_minutes=60,
    ),
    TaskDefinition(
        key="conference.seating_setup",
        name="Auditorium Seating & Executive Row Alignment",
        description="Arrange theatre rows, set VIP reserved seating markers, ensure aisle safety clearances",
        priority=ObjectivePriority.HIGH,
        phase="SETUP",
        required_provider_category="LOGISTICS",
        is_critical=False,
        estimated_duration_minutes=90,
    ),
    TaskDefinition(
        key="conference.stage_setup",
        name="Keynote Stage, Lectern & Backdrop Rigging",
        description="Position stage risers, set keynote lectern, erect tension-fabric branded backdrop",
        priority=ObjectivePriority.HIGH,
        phase="SETUP",
        required_provider_category="STAGE",
        is_critical=False,
        estimated_duration_minutes=90,
    ),
    TaskDefinition(
        key="conference.av_setup",
        name="Auditorium Audio System & PA Installation",
        description="Install line-arrays, calibrate room EQ for vocal clarity, position confidence monitors",
        priority=ObjectivePriority.CRITICAL,
        phase="SETUP",
        required_provider_category="AV_LIGHTING",
        is_critical=True,
        estimated_duration_minutes=90,
    ),
    TaskDefinition(
        key="conference.mic_setup",
        name="Wireless Microphone Pairing & Frequency Tuning",
        description="Scan RF spectrum for interference, pair keynote bodypack transmitters and Q&A mics",
        priority=ObjectivePriority.HIGH,
        phase="SETUP",
        required_provider_category="AV_LIGHTING",
        is_critical=True,
        estimated_duration_minutes=45,
    ),
    TaskDefinition(
        key="conference.display_setup",
        name="Main Presentation Video Wall & Switcher Setup",
        description="Align LED tiles or calibrate laser projector lens, connect seamless matrix switchers",
        priority=ObjectivePriority.HIGH,
        phase="SETUP",
        required_provider_category="AV_LIGHTING",
        is_critical=True,
        estimated_duration_minutes=90,
    ),
    TaskDefinition(
        key="conference.registration_setup",
        name="Registration Desk & Badge Terminal Setup",
        description="Configure badge printers, verify QR code check-in tablets, organize lanyard trays",
        priority=ObjectivePriority.HIGH,
        phase="SETUP",
        required_provider_category="LOGISTICS",
        is_critical=False,
        estimated_duration_minutes=60,
    ),
    TaskDefinition(
        key="conference.connectivity_check",
        name="High-Density Wi-Fi & Live Stream Speed Test",
        description="Verify bandwidth thresholds across access points and test backup cellular failover",
        priority=ObjectivePriority.CRITICAL,
        phase="SETUP",
        required_provider_category="LOGISTICS",
        is_critical=True,
        estimated_duration_minutes=45,
    ),
    TaskDefinition(
        key="conference.catering_setup",
        name="Coffee Break & Networking Luncheon Setup",
        description="Set urns, lay breakfast pastries, establish beverage recycling and water stations",
        priority=ObjectivePriority.MEDIUM,
        phase="SETUP",
        required_provider_category="CATERING",
        is_critical=False,
        estimated_duration_minutes=60,
    ),
    TaskDefinition(
        key="conference.final_tech_check",
        name="Dry-Run Keynote Rehearsal & AV Tech Cue Check",
        description="Test speaker slide remotes, audio video sync, lighting cues, and timer clocks",
        priority=ObjectivePriority.CRITICAL,
        phase="SETUP",
        required_provider_category="AV_LIGHTING",
        is_critical=True,
        estimated_duration_minutes=45,
    ),
    TaskDefinition(
        key="conference.readiness_verification",
        name="Conference Operational Readiness Verification",
        description="Lead organizer walkthrough and formal clearance for attendee registration opening",
        priority=ObjectivePriority.CRITICAL,
        phase="SETUP",
        required_provider_category="VENUE",
        is_critical=True,
        estimated_duration_minutes=30,
    ),
]
